//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDUsingEntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class apgEntities : DbContext
    {
        public apgEntities()
            : base("name=apgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<TipoPermiso> TipoPermiso { get; set; }
    
        public virtual ObjectResult<Nullable<int>> dia(string fi, string ff)
        {
            var fiParameter = fi != null ?
                new ObjectParameter("fi", fi) :
                new ObjectParameter("fi", typeof(string));
    
            var ffParameter = ff != null ?
                new ObjectParameter("ff", ff) :
                new ObjectParameter("ff", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dia", fiParameter, ffParameter);
        }
    }
}
